---
title: "Mini-Project 2"
author: "Grace Wagner and Nathanael Kovscek"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Front Matter
```{r warnings = FALSE, message = FALSE}
# Load necessary libraries
library(tidyverse)
library(ggplot2)
library(lubridate)

#Part 1
library(readxl)
CODGames2_mp <- read_excel("data/CODGames2_mp.xlsx")
```

## Task 1

## Task 2

## Task 3
```{r}
Results2 <- CODGames2_mp %>%
  separate(Result, into = c("PlayersTeam", "OtherTeam"), sep = "-", convert = TRUE)

PlayerTeamResult <- Results2$PlayersTeam - Results2$OtherTeam

PlayerTeamWin = 0
PlayerTeamLose = 0
PlayerTeamTie = 0

for (i in 1:length(CODGames2_mp$Result)){
  ifelse(PlayerTeamResult[i] > 0, PlayerTeamWin <- PlayerTeamWin + 1, PlayerTeamWin)
  ifelse(PlayerTeamResult[i] < 0, PlayerTeamLose <- PlayerTeamLose + 1, PlayerTeamLose)
  ifelse(PlayerTeamResult[i] == 0, PlayerTeamTie <- PlayerTeamTie + 1, PlayerTeamTie)
}

ResultsTable = data.frame("Wins" = PlayerTeamWin, "Loses" = PlayerTeamLose, "Ties" = PlayerTeamTie)
ResultsTable
```
## Task 4
Inference Question: 

How does the player's performance affect the team's performance (margin which they win)?

Team's Performance using ResultsData
```{r}
Results2 <- Results2 %>%
  mutate(GameResult = Results2$PlayersTeam - Results2$OtherTeam) %>%
  mutate(GameResult2 = case_when(GameResult > 0 ~ "win", GameResult < 0 ~ "lose", GameResult == 0 ~ "tie")) %>%
  mutate(win = ifelse(GameResult2 == "win", 1, 0),
         lose = ifelse(GameResult2 == "lose", 2, 0))

reg_res <- lm(TotalXP ~ win, data = Results2)
summary(reg_res)
reg_res <- lm(TotalXP ~ lose, data = Results2)
summary(reg_res)
```

I am testing an edit.
